// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.IO;
namespace DiabetesPrediction.ML;

public partial class DiabetesPredictions
{
    /// <summary>
    /// model input class for DiabetesPredictions.
    /// </summary>
    #region model input class
    public class ModelInput
    {
        [ColumnName(@"preg")]
        public float Preg { get; set; }

        [ColumnName(@"plas")]
        public float Plas { get; set; }

        [ColumnName(@"pres")]
        public float Pres { get; set; }

        [ColumnName(@"skin")]
        public float Skin { get; set; }

        [ColumnName(@"insu")]
        public float Insu { get; set; }

        [ColumnName(@"mass")]
        public float Mass { get; set; }

        [ColumnName(@"pedi")]
        public float Pedi { get; set; }

        [ColumnName(@"age")]
        public float Age { get; set; }

        [ColumnName(@"class")]
        public string Class { get; set; }

    }

    #endregion

    /// <summary>
    /// model output class for DiabetesPredictions.
    /// </summary>
    #region model output class
    public class ModelOutput
    {
        [ColumnName(@"preg")]
        public float Preg { get; set; }

        [ColumnName(@"plas")]
        public float Plas { get; set; }

        [ColumnName(@"pres")]
        public float Pres { get; set; }

        [ColumnName(@"skin")]
        public float Skin { get; set; }

        [ColumnName(@"insu")]
        public float Insu { get; set; }

        [ColumnName(@"mass")]
        public float Mass { get; set; }

        [ColumnName(@"pedi")]
        public float Pedi { get; set; }

        [ColumnName(@"age")]
        public float Age { get; set; }

        [ColumnName(@"class")]
        public uint Class { get; set; }

        [ColumnName(@"Features")]
        public float[] Features { get; set; }

        [ColumnName(@"PredictedLabel")]
        public string PredictedLabel { get; set; }

        [ColumnName(@"Score")]
        public float[] Score { get; set; }

    }

    #endregion

    private static string MLNetModelPath = Path.GetFullPath("DiabetesPredictions.zip");

    public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

    /// <summary>
    /// Use this method to predict on <see cref="ModelInput"/>.
    /// </summary>
    /// <param name="input">model input.</param>
    /// <returns><seealso cref=" ModelOutput"/></returns>
    public static ModelOutput Predict(ModelInput input)
    {
        var predEngine = PredictEngine.Value;
        return predEngine.Predict(input);
    }

    private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
    {
        var mlContext = new MLContext();
        ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
        return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
    }
}
